basePath: /
definitions:
  dto.ResponseError:
    properties:
      error:
        type: string
    type: object
  dto.ResponseMessageWithData:
    properties:
      message:
        type: string
      result:
        $ref: '#/definitions/dto.Song'
    type: object
  dto.Song:
    properties:
      group:
        type: string
      id:
        type: integer
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
  dto.SongRequest:
    properties:
      group:
        type: string
      song:
        type: string
    required:
    - group
    - song
    type: object
host: localhost:8080
info:
  contact: {}
  description: Тестовое задание
  title: Online song library
  version: "1.0"
paths:
  /song:
    post:
      consumes:
      - application/json
      description: Создаёт запись о новой песне
      parameters:
      - description: Данные песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/dto.SongRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.ResponseMessageWithData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseError'
      summary: Добавление новой песни
      tags:
      - Songs
  /song/{song_id}:
    delete:
      consumes:
      - application/json
      description: Удаляет песню
      parameters:
      - description: ID песни
        in: path
        name: song_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseMessageWithData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseError'
      summary: Удаление песни
      tags:
      - Songs
    patch:
      consumes:
      - application/json
      description: Обновляет поля group и song в песни
      parameters:
      - description: ID песни
        in: path
        name: song_id
        required: true
        type: integer
      - description: Обновляемые данные
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/dto.SongRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseMessageWithData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseError'
      summary: Обновление данных песни
      tags:
      - Songs
  /songs:
    get:
      consumes:
      - application/json
      description: Возвращает список песен с пагинацией и фильтрацией
      parameters:
      - description: Фильтр по группе
        in: query
        name: group
        type: string
      - description: Фильтр по названию песни
        in: query
        name: song
        type: string
      - description: Номер страницы
        in: query
        name: page
        type: integer
      - description: Лимит на страницу
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/dto.Song'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseError'
      summary: Получение списка песен
      tags:
      - Songs
  /songs/{song_id}:
    get:
      consumes:
      - application/json
      description: Возвращает текст песен с пагинацией по куплетам
      parameters:
      - description: ID песни
        in: path
        name: song_id
        required: true
        type: integer
      - description: Номер страницы
        in: query
        name: page
        type: integer
      - description: Лимит на страницу
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                type: string
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ResponseError'
      summary: Получение текста песен
      tags:
      - Songs
swagger: "2.0"
